### ISSUE TITLE
No menu item shown for web solutions?

### ISSUE THREAD

**Issue by rbadapanda** [nkahoang/VsFARMenu#1]
Repro:
Clone https://github.com/Microsoft/PowerBI-visuals
Open the solution in VS 2015.

Issue: the context menu items "Find in ..."/"Replace in ..." don't show up.

**Comment by pieter-j-steltix** [comment]
It is caused by the extension settings, because of different project structures, you need to add extra targets for where the menu appears, I did this previously in a local copy, but don't have that code anymore, but still a problem in 2019, also do not work for cordova projects or when you open a folder and not a project
